# pyOCD debugger
# Copyright (c) 2026 Arm Limited
# SPDX-License-Identifier: Apache-2.0

"""Validate gdbserver scenario docstrings and generate their README."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
import inspect
from pathlib import Path
import re
from typing import Mapping, Sequence


_SECTION_NAMES = (
    "Purpose",
    "Test method",
    "Expected result",
    "Failure indicates",
)

_OPTIONAL_SECTION_NAMES = (
    "Skip",
)

_CLIENT_FILE_ORDER = {
    "rsp": (
        "test_mailbox_smoke.py",
        "test_no_client.py",
        "test_protocol.py",
        "test_breakpoint.py",
        "test_breakpoint_capacity.py",
        "test_execution.py",
        "test_reset.py",
        "test_fault_sleep.py",
        "test_semihosting.py",
        "test_rtt.py",
        "test_swv.py",
        "test_clients.py",
        "test_two_clients.py",
        "test_flash.py",
    ),
    "arm_gdb": (
        "test_mailbox_smoke.py",
        "test_gdb_client.py",
        "test_breakpoint.py",
        "test_execution.py",
        "test_reset.py",
        "test_fault_sleep.py",
        "test_semihosting.py",
        "test_rtt.py",
        "test_clients.py",
        "test_two_clients.py",
    ),
}

_CLIENT_TITLES = {
    "rsp": "Raw RSP scenarios",
    "arm_gdb": "Arm GDB scenarios",
}

_README_HEADER = """# GDB Server Hardware Scenarios

This file is generated from the structured docstring on every test in
`rsp/test_*.py` and `arm_gdb/test_*.py`. Edit the test docstring first, then
run:

```powershell
venv\\Scripts\\python.exe test\\e2e\\gdbserver\\runner\\scenario_docs.py
```

Use `--check` to verify that the committed README is current without writing
it. Pytest collection also rejects a hardware scenario whose docstring omits
its purpose, numbered procedure, expected result, or failure diagnosis.

The order below is the recommended manual bring-up order. Pytest may execute
independent tests in another order. Each exact test node can replace the test
path in the pytest command documented in `../README.md`.

## Current scope

These scenarios cover one Cortex-M core. TrustZone secure/non-secure debugging
and multicore debugging are intentionally deferred; they are not represented
as passing, skipped, or partially implemented scenarios in this version.

The B-U585I-IOT02A is the first target implementation. The scenarios remain
target-independent by using the common test-firmware mailbox ABI and declared
target capabilities.

## Terminology

| Term | Meaning in these tests |
|---|---|
| GDB | The host debugger selected explicitly with `--gdbserver-gdb`. |
| pyOCD gdbserver | The server under test between a host client and the debug probe. |
| RSP | GDB Remote Serial Protocol packets sent directly by the lightweight test client. |
| Mailbox | A deterministic RAM structure through which the host requests firmware actions and reads results. |
| SPIN | A firmware command that stays active until the host writes its release sequence. |
| Controller | A client that starts, stops, or resumes target execution. |
| Observer | A second client used to inspect the same target and shared server state. |
| RTT | SEGGER Real Time Transfer data moved through target RAM buffers. |
| SWV | Serial Wire Viewer bytes generated by ITM and collected through the probe's SWO path. |
| Semihosting | Firmware requests that pyOCD services on the host, including console and file operations. |
"""


@dataclass(frozen=True)
class _ScenarioDocumentation:
    """Structured documentation for one collected scenario function."""

    client: str
    source_name: str
    test_name: str
    sections: Mapping[str, tuple[str, ...]]

    @property
    def node_id(self) -> str:
        """Return the repository-relative exact pytest node."""
        return "test/e2e/gdbserver/scenarios/%s/%s::%s" % (
            self.client, self.source_name, self.test_name)


def validate_scenario_docstring(docstring: str | None, test_name: str) -> None:
    """Raise ValueError if a scenario docstring is incomplete or malformed."""
    _parse_docstring(docstring, test_name)


def _parse_docstring(docstring: str | None,
                     test_name: str) -> Mapping[str, tuple[str, ...]]:
    if not docstring:
        raise ValueError("%s has no docstring" % test_name)

    lines = inspect.cleandoc(docstring).splitlines()
    header_indexes: dict[str, int] = {}
    inline_content: dict[str, str] = {}
    for section_name in _SECTION_NAMES + _OPTIONAL_SECTION_NAMES:
        header = section_name + ":"
        for line_index, line in enumerate(lines):
            if line == header or line.startswith(header + " "):
                header_indexes[section_name] = line_index
                inline_content[section_name] = line[len(header):].strip()
                break
        else:
            if section_name in _OPTIONAL_SECTION_NAMES:
                continue
            raise ValueError("%s docstring is missing %r" % (test_name, header))

    present_sections = tuple(
        name for name in _SECTION_NAMES + _OPTIONAL_SECTION_NAMES
        if name in header_indexes)
    indexes = [header_indexes[name] for name in present_sections]
    if indexes != sorted(indexes):
        raise ValueError("%s docstring sections are out of order" % test_name)

    sections: dict[str, tuple[str, ...]] = {}
    for index, section_name in enumerate(present_sections):
        first = header_indexes[section_name] + 1
        last = (header_indexes[present_sections[index + 1]]
                if index + 1 < len(present_sections) else len(lines))
        section_lines = list(lines[first:last])
        if inline_content[section_name]:
            section_lines.insert(0, inline_content[section_name])
        content = tuple(_trim_blank_lines(section_lines))
        if not content:
            raise ValueError("%s docstring has an empty %s section" % (test_name, section_name))
        sections[section_name] = content

    step_numbers = [
        int(match.group(1))
        for line in sections["Test method"]
        if (match := re.match(r"^(\d+)\.\s+", line)) is not None
    ]
    if len(step_numbers) < 2:
        raise ValueError("%s Test method must contain at least two numbered steps" % test_name)
    if step_numbers != list(range(1, len(step_numbers) + 1)):
        raise ValueError("%s Test method steps must be numbered consecutively from 1" % test_name)
    return sections


def _trim_blank_lines(lines: Sequence[str]) -> Sequence[str]:
    first = 0
    last = len(lines)
    while first < last and not lines[first].strip():
        first += 1
    while last > first and not lines[last - 1].strip():
        last -= 1
    return lines[first:last]


def _ordered_sources(client_directory: Path, client: str) -> Sequence[Path]:
    sources = {path.name: path for path in client_directory.glob("test_*.py")}
    ordered = [sources.pop(name) for name in _CLIENT_FILE_ORDER[client] if name in sources]
    ordered.extend(sources[name] for name in sorted(sources))
    return ordered


def _collect_scenarios(scenarios_directory: Path) -> Sequence[_ScenarioDocumentation]:
    scenarios: list[_ScenarioDocumentation] = []
    for client in _CLIENT_FILE_ORDER:
        client_directory = scenarios_directory / client
        for source in _ordered_sources(client_directory, client):
            tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
            for node in tree.body:
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if not node.name.startswith("test_"):
                    continue
                docstring = ast.get_docstring(node, clean=True)
                sections = _parse_docstring(docstring, "%s/%s" % (source.name, node.name))
                scenarios.append(_ScenarioDocumentation(
                    client=client,
                    source_name=source.name,
                    test_name=node.name,
                    sections=sections,
                ))
    return scenarios


def _human_title(value: str) -> str:
    words = value.removeprefix("test_").replace("_", " ").split()
    special = {
        "ctrl": "Ctrl",
        "gdb": "GDB",
        "itm": "ITM",
        "rtt": "RTT",
        "rsp": "RSP",
        "swv": "SWV",
        "wfi": "WFI",
    }
    title = " ".join(special.get(word, word) for word in words)
    return title[:1].upper() + title[1:]


def _render_section(lines: Sequence[str]) -> str:
    return "\n".join(lines)


def _render_readme(scenarios: Sequence[_ScenarioDocumentation]) -> str:
    output = [_README_HEADER.rstrip(), ""]
    for client in _CLIENT_FILE_ORDER:
        output.extend(("## " + _CLIENT_TITLES[client], ""))
        source_name = None
        for scenario in (item for item in scenarios if item.client == client):
            if scenario.source_name != source_name:
                source_name = scenario.source_name
                output.extend(("### " + _human_title(Path(source_name).stem), ""))
            output.extend((
                "#### " + _human_title(scenario.test_name),
                "",
                "- Exact test: `%s`" % scenario.node_id,
                "",
                "**Purpose**",
                "",
                _render_section(scenario.sections["Purpose"]),
                "",
                "**Test method**",
                "",
                _render_section(scenario.sections["Test method"]),
                "",
                "**Expected result**",
                "",
                _render_section(scenario.sections["Expected result"]),
                "",
                "**Failure indicates**",
                "",
                _render_section(scenario.sections["Failure indicates"]),
                "",
            ))
            if "Skip" in scenario.sections:
                output.extend((
                    "**Skip condition**",
                    "",
                    _render_section(scenario.sections["Skip"]),
                    "",
                ))
    return "\n".join(output).rstrip() + "\n"


def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if README.md differs from the scenario docstrings")
    arguments = parser.parse_args()

    scenarios_directory = Path(__file__).resolve().parents[1] / "scenarios"
    readme_path = scenarios_directory / "README.md"
    rendered = _render_readme(_collect_scenarios(scenarios_directory))
    if arguments.check:
        current = readme_path.read_text(encoding="utf-8") if readme_path.is_file() else ""
        if current != rendered:
            parser.error("%s is not synchronized with scenario docstrings" % readme_path)
        return 0

    with readme_path.open("w", encoding="utf-8", newline="\r\n") as readme:
        readme.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
