/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'GDBServerTest.Debug+AppKit-E7-M55-HP'
 * Target:  'Debug+AppKit-E7-M55-HP'
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
// enabling global pre includes
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
